### ISSUE TITLE
Block receipts missing, can't freeze

### ISSUE THREAD

**Issue by jgongil** [multi-geth/multi-geth#134]
Hi there,

Documenting here a potential bug in the client.

I started syncing the ethereum classic mainnet from scratch with the multigeth 1.9.7 as an archival node.
When it reached block [8583945 ](https://classic.etccoopexplorer.com/blocks/8583945/transactions) it slowed down the sync speed significantly and started to report the errors described below. They are always referencing this same block which contains 2 transactions.

#### System information

instance: MultiGeth/v1.9.7-stable-1efafb5f/linux-amd64/go1.13.5
OS & Version: Red Hat Enterprise Linux Server 7.6 (Maipo)

#### Expected behaviour

- No "freeze" errors.
- Higher synchronization speed

#### Actual behaviour

```
...
geth[25315]: ERROR[02-26|09:07:16.639] Block receipts missing, can't freeze     number=8583945 hash=c93eb9…25a6d2
geth[25315]: INFO [02-26|09:07:16.639] Deep froze chain segment                 blocks=0  elapsed=67.157ms  number=8583944
geth[25315]: ERROR[02-26|09:08:16.692] Block receipts missing, can't freeze     number=8583945 hash=c93eb9…25a6d2
geth[25315]: INFO [02-26|09:08:16.694] Deep froze chain segment                 blocks=0  elapsed=54.491ms  number=8583944
geth[25315]: INFO [02-26|09:08:38.815] Imported new chain segment               blocks=2  txs=6   mgas=0.958 elapsed=1m26.300s
...
```

#### Steps to reproduce the behaviour

sync status: at block: 8942813 (Tue, 08 Oct 2019 09:15:45 UTC)
service config:  --classic --syncmode full --gcmode archive

#### Comments

- Could it be related to geth issue [20239](https://github.com/ethereum/go-ethereum/issues/20239)?
- Is there any workaround?

Many thanks in advance

**Comment by sorpaas** [comment]
Geth allows you to reset blocks to a past number, so as a workaround, I think what you can do is to reset block to `8942813`, and then let it sync from that point again.

**Comment by sorpaas** [comment]
Also, please upgrade to 1.9.10 as there's a lot of fixes since 1.9.7.

**Comment by jgongil** [comment]
Dear @sorpaas,
Thank you very much for the suggestion of the workaround: I set the head back to a thousand blocks before the conflicting one `8582945` and let it sync again. 

Currently it is quite slow with the Oct 19 synchronization and I´m planning to upgrade it to 1.9.10 today.
Thanks again

**Comment by YuriyWintermute** [comment]
hey @jgongil , how do you set head back? Every place mentions it can be done but could find how anywhere...

**Comment by ph4r05** [comment]
> hey @jgongil , how do you set head back? Every place mentions it can be done but could find how anywhere...

Start with `geth console` (or `geth attach` for attaching to a running node), then:

```
debug.setHead('0x82f339')
```

**Comment by jgongil** [comment]
> hey @jgongil , how do you set head back? Every place mentions it can be done but could find how anywhere...

Apologies for this late reply. As well indicated by @ph4r05, you should use [debug_setHead](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#debug_sethead). If you are having synchronization issues I´d recommend:

1. Start geth without synchronization. You can achieve this by using your current geth configuration with the minimum modules enabled and avoiding synchronization with the flag `--maxpeers 0`
2. In new console, attach to the node through IPC and run `debug.setHead(number)` where number is your new head block in hexadecimal.

- This can take a long time: ~1h to go back 400K blocks of the mainnet.
- When finished, the command will return `null`

**Comment by datacoder-io** [comment]
I want to use `debug.setHead(0x13D620)`

but i got this error:

```
Error: invalid argument 0: json: cannot unmarshal non-string into Go value of type hexutil.Uint64
       at web3.js:6405:37(47)
       at web3.js:5115:62(37)
       at <eval>:1:14(4)
```


**Update**

Must set string value `debug.setHead('0x13D620')`

**Comment by gabrieledm** [comment]
Hi,
I'm facing the error for a geth instance running through DAppNode.

The specific error is

`ERROR[05-07|14:58:05.429] Error in block freeze operation          err="block receipts missing, can't freeze block 19118175"`

I already tried to use the command

`debug.setHead('0x12E68E1')`

but if i try to reset the head by too many blocks the command returns the error `Error: request timed out`.

I also tried to reset head by only 50 blocks but the command remains in a "pending" state and seems to not terminate.

In addition by checking the logs of geth I don't recognize the block number for the  head as I expect to see after the reset.

There is something else I can do to fix the issue ?

**Comment by gabrieledm** [comment]
> Hi, I'm facing the error for a geth instance running through DAppNode.
> 
> The specific error is
> 
> `ERROR[05-07|14:58:05.429] Error in block freeze operation err="block receipts missing, can't freeze block 19118175"`
> 
> I already tried to use the command
> 
> `debug.setHead('0x12E68E1')`
> 
> but if i try to reset the head by too many blocks the command returns the error `Error: request timed out`.
> 
> I also tried to reset head by only 50 blocks but the command remains in a "pending" state and seems to not terminate.
> 
> In addition by checking the logs of geth I don't recognize the block number for the head as I expect to see after the reset.
> 
> There is something else I can do to fix the issue ?

Update about the problem.

After several hours the node synced up and the error message is gone too.
