### ISSUE TITLE
Anyone meet this error? 1.9.12 version,testnet

### ISSUE THREAD

**Issue by rocqina** [multi-geth/multi-geth#140]
INFO [03-18|03:38:46.154] Imported new block headers               count=192  elapsed=62.031ms  number=4657 hash=5eb9df…74c0e7 age=3y4mo1w
INFO [03-18|03:38:46.402] Imported new block receipts              count=1530 elapsed=319.224ms number=1805 hash=9c5336…a2d1b0 age=3y4mo1w   size=891.23KiB
INFO [03-18|03:38:46.432] Imported new state entries               count=771  elapsed=28.978ms  processed=29979 pending=16297 retry=0   duplicate=0 unexpected=0
INFO [03-18|03:38:46.887] Imported new state entries               count=768  elapsed=24.532ms  processed=30747 pending=16494 retry=0   duplicate=0 unexpected=0
INFO [03-18|03:38:47.767] Imported new state entries               count=1152 elapsed=22.526ms  processed=31899 pending=15970 retry=0   duplicate=0 unexpected=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x52cf6e]

goroutine 12821 [running]:
math/big.(*Int).Cmp(0xc06ef11d40, 0x0, 0x1963f80f95a26c42)
        /opt/hostedtoolcache/go/1.13.8/x64/src/math/big/int.go:326 +0x2e
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).synchronise(0xc0005a2620, 0xc050db0ea0)
        /home/vsts/work/1/s/eth/sync.go:196 +0x182
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).syncer
        /home/vsts/work/1/s/eth/sync.go:177 +0x289
INFO [03-18|03:38:49.386] Maximum peer count                       ETH=200 LES=0 total=200
INFO [03-18|03:38:49.386] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
ERROR[03-18|03:38:49.387] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[03-18|03:38:49.387] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[03-18|03:38:49.387] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[03-18|03:38:49.387] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[03-18|03:38:49.387] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[03-18|03:38:49.387] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
INFO [03-18|03:38:49.389] Starting peer-to-peer node               instance=MultiGeth/v1.9.10-stable-1f8eefa1/linux-amd64/go1.13.8
INFO [03-18|03:38:49.389] Allocated trie memory caches             clean=512.00MiB dirty=512.00MiB
INFO [03-18|03:38:49.389] Allocated cache and file handles         database=/root/.ethereum/testnet/geth/chaindata cache=1024.00MiB handles=524288
INFO [03-18|03:38:50.167] Opened ancient database                  database=/root/.ethereum/testnet/geth/chaindata/ancient
ERROR[03-18|03:38:50.168] Current full block number unavailable    hash=97be80…9a3433
INFO [03-18|03:38:50.176] Persisted trie from memory database      nodes=355 size=50.41KiB time=982.408µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [03-18|03:38:50.176] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Constantinople: 4230000 Petersburg: 4939394 Istanbul: 6485846, Muir Glacier: 7117117, Engine: ethash}"
INFO [03-18|03:38:50.176] Disk storage enabled for ethash caches   dir=/root/.ethereum/testnet/geth/ethash count=3
INFO [03-18|03:38:50.176] Disk storage enabled for ethash DAGs     dir=/root/.ethash                       count=2
INFO [03-18|03:38:50.176] Initialising Ethereum protocol           versions="[65 64 63]" network=3 dbversion=7
WARN [03-18|03:38:50.177] Head block missing, resetting chain      hash=97be80…9a3433
WARN [03-18|03:38:50.177] Rewinding blockchain                     target=0
WARN [03-18|03:38:50.177] Head block missing, resetting chain      hash=97be80…9a3433
WARN [03-18|03:38:50.177] Rewinding blockchain                     target=0
ERROR[03-18|03:38:50.389] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[03-18|03:38:50.390] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[03-18|03:38:50.390] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[03-18|03:39:50.169] Current full block number unavailable    hash=97be80…9a3433
ERROR[03-18|03:40:50.171] Current full block number unavailable    hash=97be80…9a3433
ERROR[03-18|03:41:50.172] Current full block number unavailable    hash=97be80…9a3433

**Comment by meowsbits** [comment]
This looks like an issue inherited from ethereum/go-ethereum, you might want to submit this report there: https://github.com/ethereum/go-ethereum/issues/new
